version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: fluentd
  kafka:
    image: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    volumes:
      - ./data:/kafka
    logging:
      driver: fluentd
