version: '2'
services:
  zk1:
    image: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: orangemi/kafka
    restart: always
    ports:
      - 9092:9092
    links:
      - zk1
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

